title: "Into the Breach"
description: "Erik Howe's Personal Blog"
url: https://www.erikhowe.dev

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
